title: microgra∇uate
author: Christos Karaneen
logo: micrograduate/book_logo.png

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/ckaraneen/micrograduate
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  recursive_update: true
  config:
    html_context:
      default_mode: light
